name: Daily Commit

on:
  schedule:
    - cron: '39 4 * * *'  # Change to your preferred time (UTC)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update timestamp
        run: |
          echo "Last updated at $(date -u)" > update.txt

      - name: Commit - 24f1001384@ds.study.iitm.ac.in
        run: |
          git config user.name "GitHub Actions"
          git config user.email "24f1001384@ds.study.iitm.ac.in"
          git add update.txt
          git commit -m "Daily update on $(date -u)" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:$(git rev-parse --abbrev-ref HEAD)
